# This workflow will install Python dependencies, run tests and lint
# with a variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: normal-form

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - name: Install poetry
      run: |
        pipx install poetry
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Setup just
      # You may pin to the exact commit or the version.
      # uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      uses: extractions/setup-just@v1
      with:
        # A valid semver specifier of the just version to install
        just-version: 1.5.0  # optional

    - name: Install Minisat
      run: |
        sudo apt install -y minisat

    - name: Install dependencies
      run: |
        just install

    - name: Lint with flake8
      run: |
        # run the linter from the justfile
        just lint

    - name: Test with pytest
      run: |
        # run the test command from the justfile
        just test
