# This workflow will install Python dependencies, run tests and lint
# with a variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: normal-form

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install poetry
      run: |
        pipx install poetry

    - name: Setup just
      uses: extractions/setup-just@v1
      with:
        just-version: 1.5.0

    - name: Install Minisat
      run: |
        sudo apt install -y minisat

    - name: Install dependencies
      run: |
        just install

    - name: Lint with flake8
      run: |
        just lint

    - name: Test with pytest
      run: |
        just test
